GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ4NTA2MDkxLCJleHAiOjE2NDg1MDYxMDZ9.zzEhneg8MKu_4uZo8byYJd0hV8Z5KGftjRtOMwJrqbE


###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ4NTA2Mjc5fQ.ZCELcOfKFgG9qNHgRLMxCLq6LbjPCI7c57TyqZquB4I"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ4NTA2Mjc5fQ.ZCELcOfKFgG9qNHgRLMxCLq6LbjPCI7c57TyqZquB4I"
}